export const pricesFeatures = [
  {
    title: "Freemium",
    description: "Ideal para probar el sistema.",
    price: "Gratis",
    yearlyPrice: "Gratis",
    period: "/mes",
    features: [
      "Máximo de 3 empleados activos.",
      "Registro manual de asistencia.",
      "Solo 1 usuario (Administrador).",
      "Sin exportaciones ni reportes.",
      "Sin roles avanzados (sin RRHH).",
      "Sin justificaciones ni permisos.",
      "Retención de datos por 7 días.",
      "Sin notificaciones ni integraciones.",
      "Sin soporte técnico.",
    ],
    buttonText: "Probar Gratis",
  },
  {
    title: "Básico",
    description: "Ideal para pequeños negocios.",
    price: "$4.990 CLP",
    yearlyPrice: "$49.900 CLP",
    period: "/mes",
    features: [
      "Hasta 10 empleados activos.",
      "Roles: Admin + RRHH.",
      "Registro de entrada, colación y salida.",
      "Justificaciones y solicitudes de permisos.",
      "Reportes básicos mensuales.",
      "Exportación a PDF.",
      "Soporte vía correo.",
      "Retención de datos por 3 meses.",
      "Acceso a funcionalidades básicas del dashboard.",
    ],
    buttonText: "Elegir Plan",
  },
  {
    title: "Silver",
    description: "Perfecto para negocios medianos.",
    price: "$9.990 CLP",
    yearlyPrice: "$99.900 CLP",
    period: "/mes",
    features: [
      "Hasta 30 empleados activos.",
      "Roles: Admin + RRHH + Empleado.",
      "Historial completo de asistencias y justificaciones.",
      "Reportes detallados (PDF, Excel, CSV).",
      "Notificaciones por correo (asistencias, rechazos, alertas).",
      "Personalización de horarios, tolerancia y plazos.",
      "Dashboard con métricas de asistencia, inasistencias, rankings.",
      "Soporte prioritario vía correo.",
      "Retención de datos por 6 meses.",
    ],
    buttonText: "Elegir Plan",
  },
  {
    title: "Gold",
    description: "Diseñado para grandes organizaciones.",
    price: "$19.990 CLP",
    yearlyPrice: "$199.900 CLP",
    period: "/mes",
    features: [
      "Hasta 50 empleados (o más con expansión).",
      "Todo lo de Silver +",
      "Integración con WhatsApp (registro, notificaciones).",
      "Reportes automáticos por correo.",
      "Exportación avanzada y filtros.",
      "Soporte prioritario con tiempo de respuesta reducido.",
      "Historial de cambios y auditorías visibles.",
      "Dashboard avanzado por roles.",
      "Retención de datos por 12 meses.",
    ],
    buttonText: "Elegir Plan",
  },
];
